# Generated by Django 5.1.6 on 2025-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0002_rename_is_admin_usuario_is_staff_usuario_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_categoria/')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_app', models.CharField(default='Biblioteca Brivo', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_app/')),
            ],
        ),
        migrations.RemoveField(
            model_name='livro',
            name='foto',
        ),
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas_livros/'),
        ),
    ]
