# Generated by Django 5.1.6 on 2025-05-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0003_categoria_configuracao_remove_livro_foto_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.URLField(blank=True, null=True),
        ),
    ]
