# Generated by Django 5.1.6 on 2025-06-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0005_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('na_fila', 'Na Fila'), ('aguardando_confirmacao', 'Aguardando Confirmação'), ('expirado', 'Expirado'), ('concluido', 'Concluído')], default='na_fila', max_length=30),
        ),
    ]
