# Generated by Django 5.2 on 2025-06-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0006_alter_reserva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
