# Generated by Django 5.1.6 on 2025-06-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0008_historicoacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
