# Generated by Django 5.2 on 2025-07-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0009_livro_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
