# Generated by Django 5.2 on 2025-07-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0010_alter_usuario_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_retirada_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_retirada_prevista',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('na_fila', 'Na Fila'), ('aguardando_retirada', 'Aguardando Retirada'), ('emprestado', 'Emprestado'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='na_fila', max_length=30),
        ),
    ]
