# Generated by Django 5.2 on 2025-07-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0011_reserva_data_retirada_prevista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro'), ('critical', 'Crítico')], default='info', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerta do Sistema',
                'verbose_name_plural': 'Alertas do Sistema',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.RemoveField(
            model_name='livro',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_emprestada',
            field=models.IntegerField(default=0, help_text='Número de exemplares atualmente emprestados.'),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_total',
            field=models.IntegerField(default=1, help_text='Número total de exemplares deste livro.'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o livro está ativo no sistema.'),
        ),
    ]
