# Generated by Django 5.2 on 2025-07-21 02:19 (ou a data da sua 0012)
# Este arquivo é uma correção para garantir que as colunas do Livro sejam adicionadas.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0012_alertasistema_remove_livro_disponivel_and_more'),
    ]

    operations = [
        # Estas operações são as que faltaram ser aplicadas corretamente no banco de dados
        # pela migração 0012, causando o erro "no such column".

        # REMOVIDO: migrations.RemoveField para 'disponivel'
        # O campo 'disponivel' (BooleanField) já pode ter sido removido ou não existe mais como campo de banco de dados.
        # Tentar removê-lo novamente causa KeyError.

        # Adiciona o campo 'quantidade_emprestada'
        migrations.AddField(
            model_name='livro',
            name='quantidade_emprestada',
            field=models.IntegerField(default=0, help_text='Número de exemplares atualmente emprestados.'),
        ),
        # Adiciona o campo 'quantidade_total'
        migrations.AddField( # <-- CORREÇÃO: Adicionado o wrapper migrations.AddField
            model_name='livro', # <-- CORREÇÃO: Adicionado model_name
            name='quantidade_total', # <-- CORREÇÃO: Adicionado name
            field=models.IntegerField(default=1, help_text='Número total de exemplares deste livro.'),
        ),
        # Altera o campo 'ativo' (para atualizar o help_text, se necessário)
        migrations.AlterField(
            model_name='livro',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o livro está ativo no sistema.'),
        ),
    ]

