# Generated by Django 5.2 on 2025-07-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0013_fix_livro_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertasistema',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, help_text="Data e hora em que a notificação deve ser publicada (se 'Público').", null=True),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='email_enviado',
            field=models.BooleanField(default=False, help_text='Indica se o e-mail desta notificação pública já foi enviado.'),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='visibilidade',
            field=models.CharField(choices=[('admin_only', 'Apenas para Administrador'), ('publico', 'Público (para Alunos e Professores)')], default='admin_only', help_text='Define quem pode ver este alerta/notificação.', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertasistema',
            name='expira_em',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a notificação deve expirar e deixar de ser visível.', null=True),
        ),
    ]
