# Generated by Django 5.2 on 2025-09-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0017_add_subgenero_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='subgenero',
        ),
    ]
