# Generated by Django 5.2 on 2025-10-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0019_add_subgenero_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
