# Generated by Django 5.2 on 2025-10-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0020_emprestimo_data_devolucao_prevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ra',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turma',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
